name: Release to PyPI

permissions:
  contents: write

on:
  push:
    tags:
    - "v*"

jobs:
  build:
    name: build dist files
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: install build
      run: python -m pip install --upgrade build

    - name: build dist
      run: python -m build

    - uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: dist/*
        if-no-files-found: error

  publish:
    environment:
      name: pypi-release

    name: release to pypi
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: artifacts
        path: dist

    - name: Push build artifacts to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

  release:
    name: write release note
    runs-on: ubuntu-latest
    needs: publish

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - run: npx changelogithub --no-group
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
